apiVersion: v1
kind: Pod
metadata:
  name: api-and-db
spec:
  hostPID: true
  restartPolicy: OnFailure
  containers:
    - name: api
      image: mbrar/oreilly-interview:latest
      ports:
        - containerPort: 5000
    - name: ormdb
      image: caedus41/oreilly-cloud-engineer-postgres:latest
      ports:
        - containerPort: 5432
